export { Table } from './Table'
export { THead } from './THead'
export { TBody } from './TBody'
export { Pagination } from './Pagination'
export type { DataTableProps, TitleTableProps, PaginatingAndSortingProps } from '../interfaces/interfaces'